import type { Metadata } from "next"
import "./style/style.scss"
import Script from "next/script"
import { SiteFooter } from "@/pkgs/client/components/SiteFooter"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Script src="/js/bootstrap.bundle.min.js" />
      <body>
        <main className="p-3">{children}</main>
        <SiteFooter />
      </body>
    </html>
  )
}
