name: Cleanup Package Versions

on:
  schedule:
    # Runs at 00:00 UTC every 10 days
    - cron: "0 0 */10 * *"
  workflow_dispatch: # Allows manual triggering

permissions:
  packages: write

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      # https://github.com/actions/delete-package-versions
      - name: "delete all packages except the latest N versions"
        uses: actions/delete-package-versions@v5
        with:
          package-name: "gpu-agent/app"
          package-type: "container"
          # note that each tag seems to have two untagged containers pushed that
          # are needed due to multi-stage builds. So we have to be careful to
          # account that each tagged version is essentially 3 "versions".
          min-versions-to-keep: 12