name: Seed Database

on:
  push:
    branches: [main]

jobs:
  seed:
    runs-on: ubuntu-24.04
    env:
      POSTGRES_PRISMA_URL: ${{ secrets.POSTGRES_PRISMA_URL }}
      EBAY_ENVIRONMENT: ${{ secrets.EBAY_ENVIRONMENT }}
      EBAY_CLIENT_ID: ${{ secrets.EBAY_CLIENT_ID }}
      EBAY_CLIENT_SECRET: ${{ secrets.EBAY_CLIENT_SECRET }}
      EBAY_AFFILIATE_CAMPAIGN_ID: ${{ secrets.EBAY_AFFILIATE_CAMPAIGN_ID }}
      NEXT_PUBLIC_DOMAIN: ${{ secrets.NEXT_PUBLIC_DOMAIN }}

    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4

      # https://turbo.build/repo/docs/guides/ci-vendors/github-actions#caching-with-github-actionscache
      - name: cache turbo build
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      # https://github.com/actions/setup-node#usage
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci
      - run: npm run build
      - name: seed database
        run: cd apps/web && npm run prisma-seed
